name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - { DISTRO: lingmo, SUITE: polaris, ARCH: amd64, TIMESTAMP: "today 00:00:00", SHA256: ""}
      fail-fast: false
    name: Test ${{ matrix.DISTRO && format('{0} ', matrix.DISTRO) }}${{ matrix.SUITE }}${{ matrix.CODENAME && format(' ({0})', matrix.CODENAME) }}${{ matrix.ARCH && format(' [{0}]', matrix.ARCH) }}${{ matrix.TIMESTAMP && format(' at {0}', matrix.TIMESTAMP) }}
    runs-on: ubuntu-20.04
    env: ${{ matrix }}
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          
      - uses: actions/checkout@v3

      - name: Set up Debian container
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/library/debian:trixie-slim
          options: -v ${{ github.workspace }}:/work
          run: |
            mkdir /work/artifacts/${ARCH}
            "/work/.validate-${DISTRO:-debian}.sh"

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.DISTRO && format('{0} ', matrix.DISTRO) }}${{ matrix.SUITE }}${{ matrix.CODENAME && format(' ({0})', matrix.CODENAME) }}${{ matrix.ARCH && format(' [{0}]', matrix.ARCH) }}${{ matrix.TIMESTAMP && format(' at {0}', matrix.TIMESTAMP) }}
          path: |
            artifacts/**
          if-no-files-found: error
