name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - { DISTRO: lingmo, SUITE: polaris, ARCH: amd64, TIMESTAMP: "today 00:00:00", SHA256: ""}
      fail-fast: false
    name: Test ${{ matrix.DISTRO && format('{0} ', matrix.DISTRO) }}${{ matrix.SUITE }}${{ matrix.CODENAME && format(' ({0})', matrix.CODENAME) }}${{ matrix.ARCH && format(' [{0}]', matrix.ARCH) }}${{ matrix.TIMESTAMP && format(' at {0}', matrix.TIMESTAMP) }}
    runs-on: ubuntu-20.04
    env: ${{ matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq binfmt-support qemu-user-static
          docker run -d --name squignix --restart always tianon/squignix
          git clone --depth 1 https://github.com/tianon/pgp-happy-eyeballs.git ~/phe
          ~/phe/hack-my-builds.sh
          rm -rf ~/phe
      - name: Build
        run: |
          mkdir -pv ./artifacts/${ARCH}/
          "./.validate-${DISTRO:-debian}.sh"

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.DISTRO && format('{0}_', matrix.DISTRO) }}${{ matrix.SUITE }}${{ matrix.CODENAME && format('_{0}', matrix.CODENAME) }}${{ matrix.ARCH && format('_{0}', matrix.ARCH) }}
          path: |
            ./artifacts/**
          if-no-files-found: error
